import AppKit
import UniformTypeIdentifiers

/// Reads the clipboard into `ShelfContent` and writes items back. Honors the markers password managers set.
public enum ShelfPasteboard {
    /// The nspasteboard.org convention: an app writing a password or a throwaway value adds one of these types
    /// alongside the data, and clipboard tools skip it. Password managers such as 1Password rely on it. The last
    /// two are older markers some apps still write.
    public static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
    ]

    /// Longer text is skipped rather than stored cut short, so what comes back out is always what went in.
    public static let maxTextLength = 200_000
    /// At most this many files from one copy.
    public static let maxFiles = 20

    /// True when the writing app marked the clipboard as private or not worth keeping. Checked on the types
    /// themselves, never on which app wrote them.
    public static func isPrivate(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains(where: privateTypes.contains)
    }

    /// What's on the pasteboard now, or nothing when it's empty or marked private. Files win over everything else
    /// (Finder also writes the file's icon and name), then a colour, then text, then an image.
    public static func read(_ pasteboard: NSPasteboard) -> [ShelfContent] {
        guard let types = pasteboard.types, !types.isEmpty, !isPrivate(types) else { return [] }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return urls.prefix(maxFiles).map { .file($0) }
        }
        let string = pasteboard.string(forType: .string)
        if types.contains(.color), let color = NSColor(from: pasteboard), let hex = hex(color) {
            return [.color(hex: hex, original: string)]
        }
        if let string, let content = classify(string) {
            return [content]
        }
        if let data = pasteboard.data(forType: .png) {
            return [.image(data, ext: "png")]
        }
        if let data = pasteboard.data(forType: .tiff) {
            // TIFF is uncompressed; keep PNG instead.
            guard let png = NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:]) else { return [] }
            return [.image(png, ext: "png")]
        }
        if let url = NSURL(from: pasteboard) as URL?, !url.isFileURL {
            return [.link(url)]
        }
        return []
    }

    /// Text as a link when it's a single web address, as a colour when it's a hex code, otherwise as text.
    /// Empty and oversized text gives nil.
    public static func classify(_ string: String) -> ShelfContent? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, string.utf16.count <= maxTextLength else { return nil }
        if !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https", url.host() != nil {
            return .link(url)
        }
        if let hex = hex(fromCode: trimmed) {
            return .color(hex: hex, original: string)
        }
        return .text(string)
    }

    /// "#F60" or "#ff6600" to "#FF6600". The "#" is required, so numbers and words never read as colours.
    public static func hex(fromCode code: String) -> String? {
        guard code.hasPrefix("#") else { return nil }
        let digits = code.dropFirst()
        guard digits.count == 3 || digits.count == 6, digits.allSatisfy(\.isHexDigit) else { return nil }
        let full = digits.count == 3 ? digits.map { "\($0)\($0)" }.joined() : String(digits)
        return "#" + full.uppercased()
    }

    public static func hex(_ color: NSColor) -> String? {
        guard let rgb = color.usingColorSpace(.sRGB) else { return nil }
        let channels = [rgb.redComponent, rgb.greenComponent, rgb.blueComponent].map { Int(($0 * 255).rounded()).clamped(0, 255) }
        return "#" + channels.map { String(format: "%02X", $0) }.joined()
    }

    public static func color(hex: String) -> NSColor? {
        guard let value = Self.hex(fromCode: hex).flatMap({ UInt32($0.dropFirst(), radix: 16) }) else { return nil }
        return NSColor(srgbRed: CGFloat((value >> 16) & 0xFF) / 255, green: CGFloat((value >> 8) & 0xFF) / 255,
                       blue: CGFloat(value & 0xFF) / 255, alpha: 1)
    }

    /// Puts an item back on the clipboard the way the app it came from would have: files as files, images as
    /// image data, links as URLs with their text, colours as a colour and their hex.
    public static func write(_ item: ShelfItem, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .link:
            if let url = item.linkURL { pasteboard.writeObjects([url as NSURL]) }
            pasteboard.setString(item.text ?? "", forType: .string)
        case .color:
            if let hex = item.colorHex, let color = color(hex: hex) { pasteboard.writeObjects([color]) }
            pasteboard.setString(item.text ?? item.colorHex ?? "", forType: .string)
        case .image:
            let path = item.degraded == true ? item.thumbnailPath : item.filePath
            guard let path, let data = try? Data(contentsOf: URL(fileURLWithPath: path)) else { return }
            if let image = NSImage(data: data) { pasteboard.writeObjects([image]) }
            if path.lowercased().hasSuffix(".png") { pasteboard.setData(data, forType: .png) }
        case .file:
            if let url = item.fileURL { pasteboard.writeObjects([url as NSURL]) }
        }
    }
}

private extension Int {
    func clamped(_ low: Int, _ high: Int) -> Int { Swift.min(Swift.max(self, low), high) }
}
